### ISSUE TITLE
[S001] Add feature to view bill informations.

### ISSUE THREAD

**Issue by KazegamiKuon** [KazegamiKuon/wb.webui#3]
Create view to show bill information. Data get from api /bill

UI using Material UI

Can follow https://www.youtube.com/watch?v=Zynx2kRqozo&list=PLeS7aZkL6GOuyJkqg5mXvU2WoKCv6zDBL

Minimum 2 commit. 1 commit about setup react typescript, other is implement features.

test noti

**Comment by KazegamiKuon** [comment]
Create view to show bill informations. Data get from api /bill

**Comment by KazegamiKuon** [comment]
test notif

**Comment by KazegamiKuon** [comment]
test

**Comment by KazegamiKuon** [comment]
test

**Comment by KazegamiKuon** [comment]
Updated @Davidpt128

**Comment by Davidpt128** [comment]
test
